server:
  port: 8099

spring:
  application:
    name: api-gateway


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: 202681513f5c0056e8d2aebe40362481fcb23949786c05db3936b8b72f936fdc

management:
  endpoints:
    web:
      exposure:
        include: "*"


springdoc:
  swagger-ui:
    urls:
      - name: ms-auth
        url: /ms-auth/api-docs
      - name: ms-student
        url: /ms-student/v3/api-docs
