spring:
  application:
    name: ms-auth

  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
      show-sql: true
