spring:
  application:
    name: ms-student


jwt:
  secret: "202681513f5c0056e8d2aebe40362481fcb23949786c05db3936b8b72f936fdc"
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/