server:
  port: 8761

spring:
  application:
    name: discovery-server
  cloud:
    inetutils:
      preferred-networks: 127.0.0.1

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"